FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Vite env variables are injected at build time
ARG VITE_API_URL
ARG VITE_API_URL_ORDER

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_API_URL_ORDER=$VITE_API_URL_ORDER

RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
