services:
  # Grocery Store Management Backend
  grocery-backend:
    build: 
      context: ./Grocery_Store_Management/backend/src
      args:
        - PORT=8000
    container_name: grocery-store-backend
    ports:
      - "8000:8000"
    env_file:
      - ./Grocery_Store_Management/backend/src/.env
    restart: unless-stopped
    networks:
      - grocery-network

  # User Management & Payment Service
  user-service:
    build: ./User_Management_and_Payment_Service/backend
    container_name: user-payment-service
    ports:
      - "8003:8003"
    env_file:
      - ./User_Management_and_Payment_Service/backend/.env
    volumes:
      - ./User_Management_and_Payment_Service/backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - grocery-network

  # Delivery Management Backend
  delivery-backend:
    build: ./Delivery_Management/backend
    container_name: delivery-service
    ports:
      - "5001:5001"
    env_file:
      - ./Delivery_Management/backend/.env
    restart: unless-stopped
    networks:
      - grocery-network

  # Order & Notification Management
  order-service:
    build: ./Order_and_Notification_Management/backend
    container_name: order-service
    ports:
      - "8004:8004"
    env_file:
      - ./Order_and_Notification_Management/backend/.env
    restart: unless-stopped
    networks:
      - grocery-network
  # Admin Frontend
  admin-frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000/api
        - VITE_API_URL_ORDER=http://localhost:8004/api
    container_name: admin-dashboard
    ports:
      - "8173:80"
    restart: unless-stopped
    networks:
      - grocery-network

  # Customer Frontend
  customer-frontend:
    build: 
      context: ./frontend-customer
      args:
        - VITE_API_URL=http://localhost:8003/api
        - VITE_API_URL_GROCERY_MANAGEMENT_SERVICE=http://localhost:8000/api
        - VITE_STRIPE_PUBLISHABLE_KEY=pk_test_51T8FA0CHMdOpXSyUdEp5T6KaDuOecXRk4IfE8Hqf15trW1kIOaXW0iyMvYOXJ7UhKyLYKXv1kInx2VQxXgiav2aU00tsvkgszS
    container_name: customer-app
    ports:
      - "8174:80"
    restart: unless-stopped
    networks:
      - grocery-network

networks:
  grocery-network:
    driver: bridge