version: "3.9"

services:
  user-service:
    build: .
    container_name: user-payment-service
    ports:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev